### ISSUE TITLE
Error building. Boost too old?

### ISSUE THREAD

**Issue by dropwhile** [wavii/darner#17]
When trying to build on centos 6.3, I get this error:

```
$ make
[  6%] Building CXX object CMakeFiles/darner.dir/src/net/handler.o
In file included from /build/darner/include/darner/queue/iqstream.h:6,
                 from /build/darner/include/darner/net/handler.h:14,
                 from /build/darner/src/net/handler.cpp:1:
/build/darner/include/darner/queue/queue.h: In member function ‘void darner::queue::put(const darner::queue::key_type&, const std::string&)’:
/build/darner/include/darner/queue/queue.h:211: error: no match for call to ‘(const boost::system::error_category) ()’
/build/darner/include/darner/queue/queue.h: In member function ‘void darner::queue::get(const darner::queue::key_type&, std::string&)’:
/build/darner/include/darner/queue/queue.h:217: error: no match for call to ‘(const boost::system::error_category) ()’
/build/darner/include/darner/queue/queue.h: In member function ‘void darner::queue::write(leveldb::WriteBatch&)’:
/build/darner/include/darner/queue/queue.h:223: error: no match for call to ‘(const boost::system::error_category) ()’
In file included from /build/darner/include/darner/net/handler.h:16,
                 from /build/darner/src/net/handler.cpp:1:
/build/darner/include/darner/util/queue_map.hpp: In constructor ‘darner::queue_map::queue_map(boost::asio::io_service&, const std::string&)’:
/build/darner/include/darner/util/queue_map.hpp:33: error: ‘struct std::basic_string<char, std::char_traits<char>, std::allocator<char> >’ has no member named ‘string’
make[2]: *** [CMakeFiles/darner.dir/src/net/handler.o] Error 1
make[1]: *** [CMakeFiles/darner.dir/all] Error 2
make: *** [all] Error 2
```

Boost version is 1.41.0 (version in centos repos).
Is this version too old?

**Comment by erikfrey** [comment]
@cactus yup, errors come from relying on an old boost.  I took a look and the errors were mostly small conventions in the boost API that have changed.  Can you try this branch and let me know if it builds for you:

https://github.com/wavii/darner/tree/older_boost_compat

**Comment by erikfrey** [comment]
@cactus if it builds can you also confirm the tests pass?

**Comment by dropwhile** [comment]
Looks like it built ok. Let me know if there is anything else you want me to test or do.

```
$ cmake .
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.41.0
-- Found the following Boost libraries:
--   thread
--   system
--   program_options
--   unit_test_framework
--   filesystem
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/darner

$ make
Scanning dependencies of target darner
[  6%] Building CXX object CMakeFiles/darner.dir/src/net/handler.o
[ 12%] Building CXX object CMakeFiles/darner.dir/src/net/request.o
[ 18%] Building CXX object CMakeFiles/darner.dir/src/util/log.o
[ 25%] Building CXX object CMakeFiles/darner.dir/src/queue/iqstream.o
[ 31%] Building CXX object CMakeFiles/darner.dir/src/queue/oqstream.o
[ 37%] Building CXX object CMakeFiles/darner.dir/src/queue/queue.o
[ 43%] Building CXX object CMakeFiles/darner.dir/src/main.o
Linking CXX executable darner
[ 43%] Built target darner
Scanning dependencies of target db
[ 50%] Building CXX object CMakeFiles/db.dir/bench/db.o
Linking CXX executable db
[ 50%] Built target db
Scanning dependencies of target test
[ 56%] Building CXX object CMakeFiles/test.dir/src/net/request.o
[ 62%] Building CXX object CMakeFiles/test.dir/src/queue/iqstream.o
[ 68%] Building CXX object CMakeFiles/test.dir/src/queue/oqstream.o
[ 75%] Building CXX object CMakeFiles/test.dir/src/queue/queue.o
[ 81%] Building CXX object CMakeFiles/test.dir/src/util/log.o
[ 87%] Building CXX object CMakeFiles/test.dir/tests/queue.o
[ 93%] Building CXX object CMakeFiles/test.dir/tests/request.o
[100%] Building CXX object CMakeFiles/test.dir/tests/main.o
Linking CXX executable test
[100%] Built target test

$ ./test
Running 19 test cases...

*** No errors detected
```

**Comment by erikfrey** [comment]
Cool.  I still recommend you get a newer boost if you plan to rely on darner in a production environment.  But I'll go ahead and merge this in.

**Comment by erikfrey** [comment]
Fixed as of 99d717607a0183a64e2054925ee75d9d011f4db6.

**Comment by dropwhile** [comment]
Is boost 1.50 new enough for production usage? I managed to scrape together a spec file for 1.50, and butchered it up to install on centos6.3.

**Comment by erikfrey** [comment]
Yeah that should work fine - we use 1.46 in prod.

**Comment by dropwhile** [comment]
sweet. Thanks!
